### PR TITLE
dijkstra.cpp

### PR DESCRIPTION
**Pull request by Parikshit0707**

### CODE REVIEW

**Comment by ritikbanger** [comment]
Please change your file name. Extension is missing. Also, file name includes spaces which is not a good thing.

**Review by Parikshit0707 — COMMENTED** [review]
changed file name and extension added

**Comment by ritikbanger** [comment]
Screenshot from 2022-10-02 10-42-02


Here is the file name. You have changed the PR name.

**Review by ritikbanger — CHANGES_REQUESTED** [review]
File name changes required

**Review by Parikshit0707 — COMMENTED** [review]
file name changed

**Comment by ritikbanger** [comment]
Don't forget to star this repository and share on your social media about this repo for hacktoberfest. Thank you for the contribution.

**Pull request merged**
