### PR TITLE
solved issue #156 spiral matrix

### PR DESCRIPTION
**Pull request by Muthulakshimi**

### CODE REVIEW

**Comment by ritikbanger** [comment]
Address #156

**Review by ritikbanger — APPROVED** [review]

**Comment by Muthulakshimi** [comment]
hi @ritikbanger it says excluded in my hacktoberfest profile for this pr is there something I'd have to do

**Comment by ritikbanger** [comment]
Don't Forget to star this repository!

**Comment by ritikbanger** [comment]
> hi @ritikbanger it says excluded in my hacktoberfest profile for this pr is there something I'd have to do

It is due to so many spammy PRs

**Pull request merged**
