### PR TITLE
Find-No-With-even-no-of-digits.java

### PR DESCRIPTION
**Pull request by xoxo16**

### CODE REVIEW

**Comment by ritikbanger** [comment]
Please change your file name. Check readme for naming conventions.

**Review by ritikbanger — CHANGES_REQUESTED** [review]
Screenshot from 2022-10-02 19-43-07


Here is the file name.

**Comment by xoxo16** [comment]
changes done. can you please check once

**Comment by ritikbanger** [comment]
> changes done. can you please check once

The filename should be something like: find_nubmer_with_even_no_of_digits.java

**Comment by xoxo16** [comment]
Done is it ok now

**Review by ritikbanger — APPROVED** [review]
Looks good

**Pull request merged**
