### PR TITLE
Create remove_duplicates.cpp

### PR DESCRIPTION
**Pull request by itz-arnav**
Problem Statement: Given a string s, remove duplicate letters so that every letter appears once and only once. You must make sure your result is the smallest in lexicographical order among all possible results.

### CODE REVIEW

**Comment by ritikbanger** [comment]
Please add more context around your problem. Comment the question too in the code, Also, for leet code problems, there is a separate folder, it would be better to add your code in that folder.

**Comment by itz-arnav** [comment]
understood sir

**Comment by ritikbanger** [comment]
> understood sir

Please do the required change and add a new commit.

**Comment by itz-arnav** [comment]
Added More programs to CodeForces Folder

**Comment by itz-arnav** [comment]
Thank you :)

**Comment by ritikbanger** [comment]
Please share on your social media about your first PR accepted on this repo!

**Pull request merged**
